// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using NUnit.Allure.Attributes;
using NUnit.Allure.Core;

namespace QA_testing_project
{
    [AllureNUnit]
    [TestFixture]
    [Parallelizable]
    public class Testcases1 : TestBase
    {

        public Testcases1() : base(BrowserTypes.Firefox) { }
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;

        [Test, Description("This test adds record to pettype")]
     
        [TestCase("Patrol")]
        [TestCase("PEREMOGA")]
        [AllureSuite("Pet Type")]
      
        public void testcase4(string name)
        {
            Pages.PetTypesPage.NavigationComponent.OpenPetTypeTab();
            Pages.PetTypesPage.ClickAddPetButton();
            Pages.PetTypesPage.ChangeNameValue(name);
            Pages.PetTypesPage.ClickAddPetButton();
        }


    }
 }
