// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class Testcase5Test {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void testcase5() {
    driver.Navigate().GoToUrl("http://20.50.171.10:8080//");
    driver.Manage().Window.Size = new System.Drawing.Size(1050, 840);
    driver.FindElement(By.CssSelector(".ownerTab")).Click();
    driver.FindElement(By.CssSelector(".open li:nth-child(1) > a")).Click();
    driver.FindElement(By.LinkText("Dmytro Feschenko")).Click();
    driver.FindElement(By.CssSelector(".addNewPet")).Click();
    driver.FindElement(By.Id("name")).Click();
    driver.FindElement(By.Id("name")).SendKeys("Klass");
    driver.FindElement(By.CssSelector(".mat-datepicker-toggle-default-icon")).Click();
    driver.FindElement(By.CssSelector(".ng-star-inserted:nth-child(2) > .mat-calendar-body-cell:nth-child(2) > .mat-calendar-body-cell-content")).Click();
    driver.FindElement(By.Id("type")).Click();
    {
      var dropdown = driver.FindElement(By.Id("type"));
      dropdown.FindElement(By.XPath("//option[. = 'lizard']")).Click();
    }
    driver.FindElement(By.CssSelector(".savePet")).Click();
    driver.Close();
  }
}
